version: '3.8'

services:
  db_ms_price:
    image: postgres:15-alpine
    container_name: db_ms_price
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: ms_price
    ports:
      - "5432:5432"
    volumes:
      - db-ms-price-data:/var/lib/postgresql/data
  db_ms_proposal:
    image: postgres:15-alpine
    container_name: db_ms_proposal
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: ms_proposal
    ports:
      - "5433:5432"
    volumes:
      - db-ms-proposal-data:/var/lib/postgresql/data
  db_ms_report:
    image: postgres:15-alpine
    container_name: db_ms_report
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: ms_report
    ports:
      - "5434:5432"
    volumes:
      - db-ms-report-data:/var/lib/postgresql/data
  keycloak:
    image: quay.io/keycloak/keycloak:20.0.2
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8180:8080"
    volumes:
      - keycloak-data:/opt/jboss/keycloak/standalone/data
    command: ["start-dev"]
  zookeeper-1:
    image: confluentinc/cp-zookeeper:7.6.1
    container_name: zookeeper-1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: zookeeper-1:2888:3888
    networks:
      - kafka-net
    extra_hosts:
      - "moby:127.0.0.1"
  kafka-1:
    image: confluentinc/cp-kafka:7.6.1
    container_name: kafka-1
    depends_on:
      - zookeeper-1
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:19092,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:19092,OUTSIDE://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    ports:
      - "9092:9092"
    networks:
      - kafka-net
    extra_hosts:
      - "moby:127.0.0.1"
  kafdrop:
    image: obsidiandynamics/kafdrop
    container_name: kafdrop
    environment:
      KAFKA_BROKERCONNECT: kafka-1:19092
    ports:
      - "9000:9000"
    networks:
      - kafka-net
    extra_hosts:
      - "moby:127.0.0.1"
  jaeger:
    image: jaegertracing/all-in-one:1.58
    container_name: jaeger
    ports:
      - "16686:16686"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5775:5775/udp"
      - "5778:5778"
      - "14268:14268"
    networks:
      - kafka-net
    extra_hosts:
      - "moby:127.0.0.1"

volumes:
  keycloak-data:
  db-ms-price-data:
  db-ms-proposal-data:
  db-ms-report-data:

networks:
  kafka-net:
    driver: bridge